# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa9fcdaf2c1d6a2755088c1720d96db95cc3fac8c8af71c0973662cd14a3d8fdf17555be2b58e9d54ace94296d61ed890e589105be9f534b7d0b7bba172367a2

test:
  secret_key_base: 0bfd9c0fddce2a3534672f859957f7944e4c64c39c3b1a96529705e1ee09be2174f506d27137f2e82591f53215ebc7aa9404ad63155d399e3a1f54d953a3ee21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
